/*
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *    http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */
package wvlet.lang.compiler.codegen

import wvlet.uni.test.UniTest
import wvlet.lang.compiler.CompilationUnit
import wvlet.lang.compiler.Compiler
import wvlet.lang.compiler.CompilerOptions
import wvlet.lang.compiler.SourceFile
import wvlet.lang.compiler.WorkEnv

/**
  * Guardrails of engine-native function definitions (#1896): a `def ... = native` without a
  * compiler implementation (e.g. generated by `wvlet catalog import`) describes a function of the
  * target database engine, so calls to it must compile to plain SQL calls
  */
class EngineNativeFunctionTest extends UniTest:

  private def generateSQL(wv: String): String =
    val compiler = Compiler(CompilerOptions(workEnv = WorkEnv(".")))
    val unit     = CompilationUnit.fromWvletString(wv)
    val result   = compiler.compileSingleUnit(unit)
    GenSQL.generateSQL(unit)(using result.context)

  private val query =
    """from [['a']] as t(x)
      |select regexp_extract_xyz(x, 'a') as r
      |""".stripMargin

  test("emit SQL identical to the unresolved baseline for an engine-native call") {
    val baseline = generateSQL(query)
    val withDef  = generateSQL(
      s"""def regexp_extract_xyz(a1: string, a2: string) in duckdb: string = native
         |
         |${query}""".stripMargin
    )
    withDef shouldBe baseline
    withDef shouldContain "regexp_extract_xyz(x, 'a')"
  }

  test("not fail a call whose arguments mismatch the collapsed signature") {
    // Overloaded engine functions collapse to a single signature, so argument checks that
    // would reject calls the engine accepts must not run
    val sql = generateSQL(
      s"""def regexp_extract_xyz(a1: string, a2: string) in duckdb: string = native
         |
         |from [['a']] as t(x)
         |select regexp_extract_xyz(x, 'a', 1, 'extra') as r
         |""".stripMargin
    )
    sql shouldContain "regexp_extract_xyz(x, 'a', 1, 'extra')"
  }

  test("inline a user-defined function nested in an engine-native call") {
    val sql = generateSQL(
      s"""def regexp_extract_xyz(a1: string, a2: string) in duckdb: string = native
         |def my_pattern(p: string): string = concat('[', p, ']')
         |
         |from [['a']] as t(x)
         |select regexp_extract_xyz(x, my_pattern('0-9')) as r
         |""".stripMargin
    )
    sql shouldContain "regexp_extract_xyz(x, concat('[', '0-9', ']'))"
  }

  test("pass through an engine-native call nested in a user-defined function body") {
    val sql = generateSQL(
      s"""def regexp_extract_xyz(a1: string, a2: string) in duckdb: string = native
         |def digits_of(v: string): string = regexp_extract_xyz(v, '[0-9]+')
         |
         |from [['a1']] as t(x)
         |select digits_of(x) as r
         |""".stripMargin
    )
    sql shouldContain "regexp_extract_xyz(x, '[0-9]+')"
  }

  test("prefer an input column over an imported function of the same name") {
    // DuckDB exports functions with common column names (age, sign, version, ...); a bare
    // identifier in a query must keep denoting the column
    val baseline = generateSQL("""from [[25]] as t(age)
        |where age > 20
        |select age
        |""".stripMargin)
    val withDef = generateSQL(s"""def age(a1: any) in duckdb: string = native
         |
         |from [[25]] as t(age)
         |where age > 20
         |select age
         |""".stripMargin)
    withDef shouldBe baseline
    withDef shouldContain "age > 20"
  }

  test("keep evaluating compiler-implemented native functions at compile time") {
    val sql = generateSQL("select ulid_string as id\n")
    // The generated ULID literal replaces the function reference
    sql shouldNotContain "ulid_string"
  }

  test("prefer the definition of the first source file for duplicated def names") {
    // The duplicate-definition machinery (#93) resolves a name defined in multiple files
    // deterministically in source file name order, so a hand-written def in a file sorting
    // before catalog/<name>/functions.wv shadows the imported one
    def unit(fileName: String, content: String): CompilationUnit = CompilationUnit(
      SourceFile.fromString(fileName, content)
    )
    val imported = unit(
      "functions.wv",
      "def my_repeat(a1: string, a2: int) in duckdb: string = native\n"
    )
    val handWritten = unit("a_defs.wv", "def my_repeat(a1: string, a2: int): string = 'local'\n")
    val queryUnit   = unit("z_query.wv", "from [['x']] as t(x)\nselect my_repeat(x, 2) as r\n")

    val compiler = Compiler(CompilerOptions(sourceFolders = Nil, workEnv = WorkEnv(".")))
    val result   = compiler.compileMultipleUnits(List(imported, handWritten), queryUnit)
    result.hasFailures shouldBe false
    val sql = GenSQL.generateSQL(queryUnit)(using result.context)
    // The hand-written body is inlined; the engine-native passthrough is shadowed
    sql shouldContain "'local'"
    sql shouldNotContain "my_repeat"
  }

end EngineNativeFunctionTest
