import { describe, it, expect, beforeAll, afterAll } from 'vitest';
import { mkdtempSync, mkdirSync, writeFileSync, rmSync } from 'node:fs';
import { tmpdir } from 'node:os';
import { join } from 'node:path';
// The workspace APIs are exposed directly on the Scala.js WvletJS module used by the LSP server.
import { WvletJS } from '../lib/main.js';
import type { LspCompletionItem, LspDiagnostic } from '../src/types.js';

// Workspace loading (#1881): once setWorkspacePath points at a project folder, the compiler
// loads its .wv sources — including catalog/<name>/<schema>.wv files generated by
// `wvlet catalog import` — so table references resolve offline in every LSP feature.

const catalogSource = `-- Generated by \`wvlet catalog import\`. DO NOT EDIT.
type orders in mydb.sales = {
  order_id: long
  status: string
}
`;

// Engine functions imported as native defs (#1896)
const functionsSource = `-- Generated by \`wvlet catalog import\`. DO NOT EDIT.
def date_trunc(a1: string, a2: timestamp) in duckdb: timestamp = native
def regexp_extract(a1: string, a2: string) in duckdb: string = native
`;

let projectDir: string;

beforeAll(() => {
  projectDir = mkdtempSync(join(tmpdir(), 'wvlet-workspace-'));
  mkdirSync(join(projectDir, 'catalog', 'mydb'), { recursive: true });
  writeFileSync(join(projectDir, 'catalog', 'mydb', 'sales.wv'), catalogSource);
  writeFileSync(join(projectDir, 'catalog', 'mydb', 'functions.wv'), functionsSource);
  writeFileSync(
    join(projectDir, 'models.wv'),
    'model completed_orders = {\n  from sales.orders\n  where status = \'completed\'\n}\n'
  );
  WvletJS.setWorkspacePath(projectDir);
});

afterAll(() => {
  // Restore the default so other test files keep seeing an empty workspace
  WvletJS.setWorkspacePath('.');
  if (projectDir) {
    rmSync(projectDir, { recursive: true, force: true });
  }
});

describe('WvletJS.setWorkspacePath', () => {
  it('resolves catalog tables in diagnostics without a database connection', () => {
    const diagnostics: LspDiagnostic[] = JSON.parse(
      WvletJS.analyzeDiagnostics('from sales.orders select order_id\n')
    );
    expect(diagnostics).toEqual([]);
  });

  it('completes column names of a catalog table', () => {
    const src = 'from sales.orders\nselect status';
    const items: LspCompletionItem[] = JSON.parse(
      WvletJS.getCompletionItems(src, 2, 'select status'.length + 1)
    );
    const columns = items.filter((i) => i.kind === 5).map((i) => i.label);
    expect(columns).toContain('order_id');
    expect(columns).toContain('status');
  });

  it('completes catalog table names when typing a dot after the schema', () => {
    const src = 'from sales.';
    const items: LspCompletionItem[] = JSON.parse(
      WvletJS.getCompletionItems(src, 1, src.length + 1)
    );
    const labels = items.map((i) => i.label);
    expect(labels).toContain('orders');
    // Member-access completion does not include keywords
    expect(labels).not.toContain('select');
  });

  it('completes columns when typing a dot after a table reference', () => {
    const src = 'from sales.orders\nselect orders.';
    const items: LspCompletionItem[] = JSON.parse(
      WvletJS.getCompletionItems(src, 2, 'select orders.'.length + 1)
    );
    const labels = items.map((i) => i.label);
    expect(labels).toContain('order_id');
    expect(labels).toContain('status');
  });

  it('completes imported engine functions with their signature', () => {
    const src = 'from sales.orders\nselect regexp';
    const items: LspCompletionItem[] = JSON.parse(
      WvletJS.getCompletionItems(src, 2, 'select regexp'.length + 1)
    );
    const fn = items.find((i) => i.label === 'regexp_extract');
    expect(fn).toBeDefined();
    // Kind 3 = Function; the detail renders the callable signature
    expect(fn?.kind).toBe(3);
    expect(fn?.detail).toBe('(a1: string, a2: string): string');
  });

  it('reports no diagnostics for a call to an imported engine function', () => {
    const diagnostics: LspDiagnostic[] = JSON.parse(
      WvletJS.analyzeDiagnostics("from sales.orders select regexp_extract(status, 'a')\n")
    );
    expect(diagnostics).toEqual([]);
  });

  it('resolves models defined in other workspace files', () => {
    const diagnostics: LspDiagnostic[] = JSON.parse(
      WvletJS.analyzeDiagnostics('from completed_orders select order_id\n')
    );
    expect(diagnostics).toEqual([]);
  });

  it('keeps diagnostics of the current document only', () => {
    // A parse error in the open document is reported even though workspace files are loaded
    const diagnostics: LspDiagnostic[] = JSON.parse(
      WvletJS.analyzeDiagnostics('from sales.orders where\n')
    );
    expect(diagnostics.length).toBeGreaterThan(0);
  });
});
