package wvlet.lang.ext

import wvlet.uni.util.ULID
import wvlet.lang.api.StatusCode

object NativeFunction:

  /**
    * Returns true when the named function is evaluated inside the compiler. A `= native` function
    * definition without a compiler implementation describes a function provided by the target
    * database engine (e.g. generated by `wvlet catalog import`), and calls to it are passed through
    * to the engine as plain SQL function calls
    */
  def isImplemented(name: String): Boolean = name == "ulid_string"

  def callByName(name: String): Any =
    name match
      case "ulid_string" =>
        ulid_string
      case _ =>
        throw StatusCode.NOT_IMPLEMENTED.newException(s"Unknown function: ${name}")

  def ulid_string: String = ULID.newULIDString
