package wvlet.lang.ext

import wvlet.uni.util.ULID
import wvlet.lang.api.StatusCode

object NativeFunction:

  /** The functions evaluated inside the compiler, by name */
  private val implementedFunctions: Map[String, () => Any] = Map(
    "ulid_string" -> (() => ulid_string)
  )

  /**
    * Returns true when the named function is evaluated inside the compiler. A `= native` function
    * definition without a compiler implementation describes a function provided by the target
    * database engine (e.g. generated by `wvlet catalog import`), and calls to it are passed through
    * to the engine as plain SQL function calls
    */
  def isImplemented(name: String): Boolean = implementedFunctions.contains(name)

  def callByName(name: String): Any =
    implementedFunctions.get(name) match
      case Some(f) =>
        f()
      case None =>
        throw StatusCode.NOT_IMPLEMENTED.newException(s"Unknown function: ${name}")

  def ulid_string: String = ULID.newULIDString
