/*
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *    http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */
package wvlet.lang.catalog

import wvlet.lang.compiler.CompilationUnit
import wvlet.lang.compiler.SourceIO
import wvlet.lang.compiler.parser.ParserPhase
import wvlet.lang.compiler.parser.WvletToken
import wvlet.lang.model.DataType
import wvlet.uni.log.LogSupport

import scala.collection.mutable
import scala.util.Try

/**
  * Exports database table schemas as Wvlet source files with schema-bound table types (#1881):
  *
  * {{{
  * type orders in mydb.sales = {
  *   order_id: bigint
  *   status: string
  * }
  * }}}
  *
  * The generated files act like a lockfile for offline query validation: committing them lets the
  * compiler, CI, and editor tooling type-check table references without a live database connection.
  * Re-running the export refreshes the files, and the output is deterministic (tables sorted by
  * name, columns in ordinal order) so `git diff` shows only real schema drift.
  */
object StaticCatalogExporter extends LogSupport:

  /** Marker heading every generated file, used to recognize importer-owned files */
  val generatedFileHeader: String = "-- Generated by `wv catalog import`. DO NOT EDIT."

  private val identifierPattern = "^[a-zA-Z][a-zA-Z0-9_]*$".r

  private val reservedKeywords: Set[String] =
    WvletToken.keywords.filter(_.isReservedKeyword).map(_.str).toSet

  /**
    * Render the tables of a single schema as Wvlet type definitions bound to
    * `<catalogName>.<schemaName>`
    */
  def generateSchemaSource(
      catalogName: String,
      schemaName: String,
      tables: Seq[Catalog.TableDef]
  ): String =
    val location = s"${quote(catalogName)}.${quote(schemaName)}"
    val header   =
      s"""${generatedFileHeader}
         |-- Table types of ${catalogName}.${schemaName}, bound for offline query validation.
         |-- Re-run `wv catalog import` to refresh; add hand-written types in your own files."""
        .stripMargin
    val typeDefs = tables
      .filter(t => isExportable(t))
      .sortBy(_.name)
      .map { table =>
        val columns = table
          .columns
          .map { c =>
            s"  ${quote(c.name)}: ${fieldType(c.dataType)}"
          }
          .mkString("\n")
        s"""type ${quote(table.name)} in ${location} = {
           |${columns}
           |}""".stripMargin
      }
    (header +: typeDefs).mkString("", "\n\n", "\n")

  /**
    * Export all (or one selected) schemas of the catalog as Wvlet sources under
    * `<basePath>/<catalogName>/<schemaName>.wv`. Returns the written file paths
    */
  def exportCatalog(
      catalog: Catalog,
      basePath: String,
      schema: Option[String] = None
  ): List[String] =
    val schemaNames =
      schema match
        case Some(s) =>
          List(catalog.getSchema(s).name)
        case None =>
          catalog.listSchemas.map(_.name).filterNot(isSystemSchema).toList
    exportSchemas(catalog.catalogName, schemaNames, catalog.listTables, basePath)

  /**
    * Export the given schemas as Wvlet sources under `<basePath>/<catalogName>/<schemaName>.wv`,
    * loading each schema's tables with `tablesOf`. Returns the written file paths
    */
  def exportSchemas(
      catalogName: String,
      schemaNames: Seq[String],
      tablesOf: String => Seq[Catalog.TableDef],
      basePath: String
  ): List[String] =
    validatePathName(catalogName)
    val written = List.newBuilder[String]
    schemaNames.foreach { schemaName =>
      validatePathName(schemaName)
      val tables = tablesOf(schemaName)
      if tables.isEmpty then
        debug(s"Skipping schema ${catalogName}.${schemaName}: no tables")
      else
        val path = s"${basePath}/${catalogName}/${schemaName}.wv"
        SourceIO.writeString(path, generateSchemaSource(catalogName, schemaName, tables))
        written += path
    }
    written.result()

  /** System schemas that are never exported */
  def isSystemSchema(name: String): Boolean = Set("information_schema", "pg_catalog", "system")
    .contains(name.toLowerCase)

  private def isExportable(table: Catalog.TableDef): Boolean =
    if table.columns.isEmpty then
      warn(s"Skipping table ${table.fullName}: no columns")
      false
    else if table.name.contains("`") then
      warn(s"Skipping table ${table.fullName}: backquotes in table names are not supported")
      false
    else
      true

  private def quote(name: String): String =
    if identifierPattern.matches(name) && !reservedKeywords.contains(name.toLowerCase) then
      name
    else
      s"`${name}`"

  private val fieldTypeCache = mutable.Map.empty[String, Boolean]

  /**
    * The Wvlet type expression of a column. Falls back to `any` (keeping the original type in a
    * comment) when the type does not round-trip through the Wvlet field-type grammar
    */
  private def fieldType(dataType: DataType): String =
    val expr    = dataType.wvExpr
    val isValid = fieldTypeCache.getOrElseUpdate(
      expr,
      Try(ParserPhase.parseOnly(CompilationUnit.fromWvletString(s"type t = {\n  c: ${expr}\n}\n")))
        .isSuccess
    )
    if isValid then
      expr
    else
      s"any -- original type: ${expr}"

  private def validatePathName(name: String): Unit =
    if name.isEmpty || name.contains("/") || name.contains("\\") || name.contains("..") then
      throw IllegalArgumentException(s"Invalid catalog/schema name: ${name}")

end StaticCatalogExporter
