/*
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *    http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */
package wvlet.lang.catalog

import wvlet.lang.api.StatusCode
import wvlet.lang.catalog.SQLFunction.FunctionType
import wvlet.lang.compiler.CompilationUnit
import wvlet.lang.compiler.SourceIO
import wvlet.lang.compiler.parser.ParserPhase
import wvlet.lang.compiler.parser.WvletToken
import wvlet.lang.compiler.typer.BuiltinFunctions
import wvlet.lang.model.DataType
import wvlet.lang.model.plan.PackageDef
import wvlet.lang.model.plan.TopLevelFunctionDef
import wvlet.uni.log.LogSupport

import scala.collection.mutable
import scala.util.Try

/**
  * Exports database table schemas as Wvlet source files with schema-bound table types (#1881):
  *
  * {{{
  * type orders in mydb.sales = {
  *   order_id: bigint
  *   status: string
  * }
  * }}}
  *
  * The generated files act like a lockfile for offline query validation: committing them lets the
  * compiler, CI, and editor tooling type-check table references without a live database connection.
  * Re-running the export refreshes the files, and the output is deterministic (tables sorted by
  * name, columns in ordinal order) so `git diff` shows only real schema drift.
  */
object StaticCatalogExporter extends LogSupport:

  /**
    * Marker heading every generated file. Files with this marker are owned by the importer: stale
    * ones (e.g. of dropped schemas) are removed on re-export, while hand-written files are never
    * touched
    */
  val generatedFileHeader: String = "-- Generated by `wvlet catalog import`. DO NOT EDIT."

  private val identifierPattern = "^[a-zA-Z][a-zA-Z0-9_]*$".r

  // Quote every keyword (also non-reserved ones): the type-body field grammar accepts only
  // plain identifier tokens, so a bare keyword column name (e.g. count) would not parse
  private val keywords: Set[String] = WvletToken.keywords.map(_.str).toSet

  private val systemSchemas = Set("information_schema", "pg_catalog", "system")

  /**
    * Render the tables of a single schema as Wvlet type definitions bound to
    * `<catalogName>.<schemaName>`
    */
  def generateSchemaSource(
      catalogName: String,
      schemaName: String,
      tables: Seq[Catalog.TableDef]
  ): String =
    val location = s"${quote(catalogName)}.${quote(schemaName)}"
    val header   =
      s"""${generatedFileHeader}
         |-- Table types of ${catalogName}.${schemaName}, bound for offline query validation.
         |-- Re-run `wvlet catalog import` to refresh; add hand-written types in your own files."""
        .stripMargin
    // Caches the per-type grammar check within this export
    val typeCache = mutable.Map.empty[String, Boolean]
    val typeDefs  = tables
      .filter(t => isExportable(t))
      .sortBy(_.name)
      .map { table =>
        val columns = table
          .columns
          .map { c =>
            s"  ${quote(c.name)}: ${fieldType(c.dataType, typeCache)}"
          }
          .mkString("\n")
        s"""type ${quote(table.name)} in ${location} = {
           |${columns}
           |}""".stripMargin
      }
    (header +: typeDefs).mkString("", "\n\n", "\n")

  /**
    * Export the given schemas as Wvlet sources under `<basePath>/<catalogName>/<schemaName>.wv`,
    * loading each schema's tables with `tablesOf`. When `pruneStale` is set (full-catalog exports),
    * previously generated files that were not re-generated in this run — e.g. of schemas dropped
    * from the database — are deleted; hand-written files are kept. Returns the written file paths
    */
  def exportSchemas(
      catalogName: String,
      schemaNames: Seq[String],
      tablesOf: String => Seq[Catalog.TableDef],
      basePath: String,
      pruneStale: Boolean = false,
      keepPaths: Seq[String] = Nil
  ): List[String] =
    validatePathName(catalogName)
    val written = List.newBuilder[String]
    schemaNames.foreach { schemaName =>
      if !isValidFolderName(schemaName) then
        // Skip only the offending schema so the rest of the catalog still imports
        warn(s"Skipping schema ${catalogName}.${schemaName}: unsupported schema name")
      else
        val tables = tablesOf(schemaName)
        if tables.isEmpty then
          debug(s"Skipping schema ${catalogName}.${schemaName}: no tables")
        else
          val path = s"${basePath}/${catalogName}/${schemaName}.wv"
          SourceIO.writeString(path, generateSchemaSource(catalogName, schemaName, tables))
          written += path
    }
    val writtenPaths = written.result()
    if pruneStale then
      pruneStaleFiles(s"${basePath}/${catalogName}", writtenPaths ++ keepPaths)
    writtenPaths

  /**
    * Export the engine functions as native Wvlet function definitions under
    * `<basePath>/<catalogName>/functions.wv` (#1896):
    *
    * {{{
    * def date_trunc(a1: string, a2: timestamp) in duckdb: timestamp = native
    * }}}
    *
    * Calls to the generated defs compile to plain SQL function calls, so engine-specific functions
    * get name completion and offline type-checking like the exported table types do. Returns the
    * written file path, or None when no exportable function was found
    */
  def exportFunctions(
      catalogName: String,
      contextName: String,
      functions: Seq[SQLFunction],
      basePath: String
  ): Option[String] =
    validatePathName(catalogName)
    val source = generateFunctionsSource(contextName, functions)
    if source.isEmpty then
      None
    else
      val path = s"${basePath}/${catalogName}/functions.wv"
      SourceIO.writeString(path, source)
      Some(path)

  /**
    * Render engine function metadata as Wvlet function definitions tagged with the engine context
    * (e.g. `in duckdb`). The generated defs must never change how an existing query compiles, so
    * function names that could collide with the Wvlet syntax or the builtin typing rules are
    * skipped, and overloaded functions collapse to a single signature with `any` argument types.
    * Returns an empty string when no function is exportable
    */
  def generateFunctionsSource(contextName: String, functions: Seq[SQLFunction]): String =
    val header =
      s"""${generatedFileHeader}
         |-- Functions of the ${contextName} engine, bound for offline query validation.
         |-- Re-run `wvlet catalog import` to refresh; add hand-written defs in your own files."""
        .stripMargin
    // Caches the per-def grammar check within this export
    val defCache = mutable.Map.empty[String, Boolean]
    val defs     = functions
      .filter(f => isExportable(f))
      .groupBy(_.name.toLowerCase)
      .toSeq
      .sortBy(_._1)
      .flatMap { case (name, overloads) =>
        renderFunctionDef(name, contextName, overloads, defCache)
      }
    if defs.isEmpty then
      ""
    else
      (header +: defs).mkString("", "\n", "\n")

  /**
    * The single Wvlet def of a function name, collapsing overloads: a single signature keeps its
    * real types (validated through the def grammar with an `any` fallback), while overloaded names
    * get `any` arguments of the widest arity, keeping the return type only when all overloads agree
    * on it. This keeps offline compilation from rejecting calls that the engine would accept
    */
  private def renderFunctionDef(
      name: String,
      contextName: String,
      overloads: Seq[SQLFunction],
      defCache: mutable.Map[String, Boolean]
  ): Option[String] =
    def render(argTypes: Seq[String], retType: Option[String]): String =
      val args =
        if argTypes.isEmpty then
          ""
        else
          argTypes
            .zipWithIndex
            .map { case (t, i) =>
              s"a${i + 1}: ${t}"
            }
            .mkString("(", ", ", ")")
      val ret = retType.map(t => s": ${t}").getOrElse("")
      s"def ${name}${args} in ${contextName}${ret} = native"

    def parses(defSource: String): Boolean = defCache.getOrElseUpdate(
      defSource,
      Try(ParserPhase.parseOnly(CompilationUnit.fromWvletString(s"${defSource}\n"))).isSuccess
    )

    val returnTypes = overloads.map(_.returnType.wvExpr).distinct
    val retType     =
      returnTypes match
        case Seq(single) =>
          Some(single)
        case _ =>
          // Overloads disagree on the return type; `any` keeps calls typed without
          // committing to a wrong type
          Some("any")
    val argTypes =
      if overloads.size == 1 then
        overloads.head.args.map(_.wvExpr)
      else
        // Overloads collapse to `any` arguments of the widest arity so that no existing call
        // can start failing on an argument-type mismatch
        Seq.fill(overloads.map(_.args.size).max)("any")

    // Degrade gracefully when a type does not round-trip through the Wvlet def grammar:
    // first the argument types, then the return type, fall back to `any`
    val candidates =
      Seq(
        render(argTypes, retType),
        render(argTypes.map(_ => "any"), retType),
        render(argTypes.map(_ => "any"), retType.map(_ => "any"))
      ).distinct
    candidates.find(parses) match
      case some @ Some(_) =>
        some
      case None =>
        warn(s"Skipping function ${name}: signature does not fit the Wvlet def grammar")
        None

  end renderFunctionDef

  /**
    * A function is exportable when its call syntax is a plain function call and its name can never
    * collide with the Wvlet syntax (keywords cannot be backquoted usefully as call syntax), the
    * builtin function typing rules, or the standard library definitions
    */
  private def isExportable(f: SQLFunction): Boolean =
    val name = f.name.toLowerCase
    exportableFunctionTypes.contains(f.functionType) && identifierPattern.matches(f.name) &&
    !keywords.contains(name) && !BuiltinFunctions.allFunctionNames.contains(name) &&
    !stdlibFunctionNames.contains(name)

  /** TABLE, PRAGMA, and MACRO functions use a different call syntax and are not exported */
  private val exportableFunctionTypes: Set[FunctionType] = Set(
    FunctionType.SCALAR,
    FunctionType.AGGREGATE,
    FunctionType.WINDOW
  )

  /** Top-level function names defined in the standard library (e.g. ulid_string) */
  private lazy val stdlibFunctionNames: Set[String] =
    CompilationUnit
      .stdLib
      .flatMap { unit =>
        Try(ParserPhase.parseOnly(unit))
          .toOption
          .toList
          .flatMap {
            case p: PackageDef =>
              p.statements
                .collect { case t: TopLevelFunctionDef =>
                  t.functionDef.name.name.toLowerCase
                }
            case _ =>
              Nil
          }
      }
      .toSet

  /** Delete previously generated .wv files under the catalog folder that were not re-written */
  private def pruneStaleFiles(catalogFolder: String, writtenPaths: List[String]): Unit =
    val keep = writtenPaths.toSet
    SourceIO
      .listFiles(catalogFolder)
      .filter(path => path.endsWith(".wv") && !keep.contains(path))
      .foreach { path =>
        val isGenerated = Try(SourceIO.readAsString(path).startsWith(generatedFileHeader))
          .getOrElse(false)
        if isGenerated then
          info(s"Removing stale catalog file ${path}")
          SourceIO.deleteFile(path)
      }

  /** System schemas that are never exported */
  def isSystemSchema(name: String): Boolean = systemSchemas.contains(name.toLowerCase)

  private def isExportable(table: Catalog.TableDef): Boolean =
    def isRenderable(name: String): Boolean = !name.exists(c => c == '`' || c.isControl)
    if table.columns.isEmpty then
      warn(s"Skipping table ${table.fullName}: no columns")
      false
    else if !isRenderable(table.name) then
      warn(s"Skipping table ${table.fullName}: unsupported characters in the table name")
      false
    else
      table.columns.filterNot(c => isRenderable(c.name)) match
        case Nil =>
          true
        case badColumns =>
          warn(
            s"Skipping table ${table.fullName}: unsupported characters in columns ${badColumns
                .map(_.name)
                .mkString(", ")}"
          )
          false

  private def quote(name: String): String =
    if identifierPattern.matches(name) && !keywords.contains(name.toLowerCase) then
      name
    else
      s"`${name}`"

  /**
    * The Wvlet type expression of a column. Falls back to `any` (keeping the original type in a
    * comment) when the type does not round-trip through the Wvlet field-type grammar
    */
  private def fieldType(dataType: DataType, typeCache: mutable.Map[String, Boolean]): String =
    val expr    = dataType.wvExpr
    val isValid = typeCache.getOrElseUpdate(
      expr,
      Try(ParserPhase.parseOnly(CompilationUnit.fromWvletString(s"type t = {\n  c: ${expr}\n}\n")))
        .isSuccess
    )
    if isValid then
      expr
    else
      s"any -- original type: ${expr}"

  /**
    * A name is usable as a catalog folder name when it cannot escape the target folder and the
    * compiler's catalog folder scan will find it again: the scan skips ignored and hidden folders,
    * so an export with such a name would silently never load back
    */
  private def isValidFolderName(name: String): Boolean =
    name.nonEmpty && !name.contains("/") && !name.contains("\\") && !name.contains("..") &&
      !name.startsWith(".") && !SourceIO.ignoredFolders.contains(name)

  private def validatePathName(name: String): Unit =
    if !isValidFolderName(name) then
      throw StatusCode
        .INVALID_ARGUMENT
        .newException(s"Name '${name}' cannot be used as a catalog folder name")

end StaticCatalogExporter
