-- Test various Trino EXPLAIN syntax variations

-- Simple EXPLAIN (backward compatibility)
EXPLAIN SELECT 1 FROM (VALUES (1)) AS t(x);

-- EXPLAIN with TYPE options
EXPLAIN (TYPE DISTRIBUTED) SELECT 1 FROM (VALUES (1)) AS t(x);
EXPLAIN (TYPE LOGICAL) SELECT 1 FROM (VALUES (1)) AS t(x);
EXPLAIN (TYPE VALIDATE) SELECT 1 FROM (VALUES (1)) AS t(x);
EXPLAIN (TYPE IO) SELECT 1 FROM (VALUES (1)) AS t(x);

-- EXPLAIN with FORMAT options
EXPLAIN (FORMAT TEXT) SELECT 1 FROM (VALUES (1)) AS t(x);
EXPLAIN (FORMAT GRAPHVIZ) SELECT 1 FROM (VALUES (1)) AS t(x);
EXPLAIN (FORMAT JSON) SELECT 1 FROM (VALUES (1)) AS t(x);

-- EXPLAIN with multiple options
EXPLAIN (TYPE DISTRIBUTED, FORMAT JSON) SELECT 1 FROM (VALUES (1)) AS t(x);
EXPLAIN (FORMAT GRAPHVIZ, TYPE LOGICAL) SELECT 1 FROM (VALUES (1)) AS t(x);
EXPLAIN (TYPE VALIDATE, FORMAT TEXT) SELECT 1 FROM (VALUES (1)) AS t(x);

-- EXPLAIN ANALYZE syntax
EXPLAIN ANALYZE SELECT 1 FROM (VALUES (1)) AS t(x);
EXPLAIN ANALYZE VERBOSE SELECT 1 FROM (VALUES (1)) AS t(x);

-- Test with more complex queries
EXPLAIN (TYPE DISTRIBUTED) SELECT t1.x, t2.y FROM (VALUES (1), (2)) AS t1(x) JOIN (VALUES (3), (4)) AS t2(y) ON t1.x = t2.y;

-- Test backward compatibility with PLAN and FOR keywords
EXPLAIN PLAN FOR SELECT 1 FROM (VALUES (1)) AS t(x);