package wvlet.lang.sdk.js

import scala.scalajs.js
import scala.scalajs.js.annotation.*
import wvlet.lang.compiler.CompilationUnit
import wvlet.lang.compiler.Compiler
import wvlet.lang.compiler.CompilerOptions
import wvlet.lang.compiler.DBType
import wvlet.lang.compiler.Symbol
import wvlet.lang.compiler.WorkEnv
import wvlet.lang.compiler.codegen.GenSQL
import wvlet.lang.api.WvletLangException
import wvlet.lang.api.StatusCode
import wvlet.lang.api.SourceLocation
import wvlet.lang.api.v1.compile.CompileResponse
import wvlet.lang.api.v1.compile.CompileError
import wvlet.lang.api.v1.compile.ErrorLocation
import wvlet.lang.BuildInfo
import wvlet.lang.compiler.parser.ParserPhase
import wvlet.lang.compiler.lsp.CompletionItem
import wvlet.lang.compiler.lsp.CompletionProvider
import wvlet.lang.compiler.lsp.DefinitionProvider
import wvlet.lang.compiler.lsp.HoverProvider
import wvlet.lang.model.plan.*
import wvlet.uni.weaver.Weaver
import wvlet.uni.weaver.codec.PrimitiveWeaver.given

import scala.collection.mutable.ListBuffer

/**
  * JavaScript API for Wvlet compiler. This provides a JSON-based interface similar to the native
  * library's wvlet_compile_query_json function.
  */
@JSExportTopLevel("WvletJS")
object WvletJS:

  /**
    * Compile a Wvlet query and return the result as JSON.
    * @param query
    *   The Wvlet query string
    * @param options
    *   JSON string with compilation options (e.g., {"target": "duckdb"})
    * @return
    *   JSON string with compilation result
    */
  @JSExport
  def compile(query: String, options: String = "{}"): String =
    try
      val opts = Weaver.of[CompileOptions].fromJson(options)

      // Create compiler with options
      val targetDB =
        opts.target.getOrElse("duckdb").toLowerCase match
          case "trino" =>
            DBType.Trino
          case _ =>
            DBType.DuckDB

      val compiler = Compiler(CompilerOptions(workEnv = WorkEnv(path = "."), dbType = targetDB))

      // Compile the query
      val inputUnit     = CompilationUnit.fromWvletString(query)
      val compileResult = compiler.compileSingleUnit(inputUnit)
      compileResult.reportAllErrors

      // Generate SQL
      val ctx = compileResult
        .context
        .withCompilationUnit(inputUnit)
        .withDebugRun(false)
        .newContext(Symbol.NoSymbol)

      val sql = GenSQL.generateSQL(inputUnit)(using ctx)

      val response = CompileResponse(success = true, sql = Some(sql))

      Weaver.of[CompileResponse].toJson(response)
    catch
      case e: WvletLangException =>
        val locationOpt =
          if e.sourceLocation != SourceLocation.NoSourceLocation then
            Some(
              ErrorLocation(
                path = e.sourceLocation.path,
                fileName = e.sourceLocation.fileName,
                line = e.sourceLocation.position.line,
                column = e.sourceLocation.position.column,
                lineContent =
                  if e.sourceLocation.codeLineAt.nonEmpty then
                    Some(e.sourceLocation.codeLineAt)
                  else
                    None
              )
            )
          else
            None

        val error = CompileError(
          statusCode = e.statusCode,
          message = e.getMessage,
          location = locationOpt
        )

        val response = CompileResponse(success = false, error = Some(error))

        Weaver.of[CompileResponse].toJson(response)

      case e: Throwable =>
        val error = CompileError(
          statusCode = StatusCode.INTERNAL_ERROR,
          message = Option(e.getMessage).getOrElse(e.getClass.getName)
        )

        val response = CompileResponse(success = false, error = Some(error))

        Weaver.of[CompileResponse].toJson(response)

  /**
    * Get the version of the Wvlet compiler
    */
  @JSExport
  def getVersion(): String = wvlet.lang.BuildInfo.version

  // Workspace folder whose .wv sources (including the well-known catalog/ folder, #1881) are
  // loaded as compilation units, so LSP features see cross-file models, types, and imported
  // table schemas
  private var workspacePath: String               = "."
  private var cachedLspCompiler: Option[Compiler] = None

  /**
    * Set the workspace root folder for LSP features. Sources in the folder — including the
    * `catalog/` folder generated by `wvlet catalog import` — are compiled together with each
    * document, enabling offline table/column resolution and cross-file references
    */
  @JSExport
  def setWorkspacePath(path: js.UndefOr[String]): Unit =
    // The path can be null or undefined when called from the JS side
    path
      .toOption
      .filter(p => p != null && p.nonEmpty && p != workspacePath)
      .foreach { p =>
        workspacePath = p
        cachedLspCompiler = None
      }

  // Cached compiler shared by the LSP features (avoids repeated initialization); rebuilt when
  // the workspace path changes. Workspace files themselves are re-scanned on every compile
  private def lspCompiler: Compiler = cachedLspCompiler.getOrElse {
    val compiler = Compiler(
      CompilerOptions(sourceFolders = List(workspacePath), workEnv = WorkEnv(path = workspacePath))
    )
    cachedLspCompiler = Some(compiler)
    compiler
  }

  private def makeDiagnostic(
      line: Int,
      column: Int,
      endLine: Int,
      endColumn: Int,
      message: String,
      statusCode: String
  ): LspDiagnostic = LspDiagnostic(
    line = line,
    column = column,
    endLine = endLine,
    endColumn = endColumn,
    message = message,
    severity = "error",
    statusCode = statusCode
  )

  /**
    * Analyze a Wvlet source and return diagnostics (errors/warnings) as JSON.
    * @param content
    *   The Wvlet source code
    * @return
    *   JSON array of diagnostics: [{line, column, endLine, endColumn, message, severity,
    *   statusCode}]
    */
  @JSExport
  def analyzeDiagnostics(content: String): String =
    val diagnostics = ListBuffer.empty[LspDiagnostic]
    val inputUnit   = CompilationUnit.fromWvletString(content)
    try
      // compileSingleUnit throws only for errors of the context unit itself: with workspace
      // sources loaded, a broken file elsewhere must not surface as a diagnostic of the
      // current document
      lspCompiler.compileSingleUnit(inputUnit)
    catch
      case e: WvletLangException =>
        val loc = e.sourceLocation
        // Use the reported position only when it points into this document: an error can
        // carry a location in another workspace file (e.g. raised while lazily typing a
        // model defined elsewhere)
        if loc != SourceLocation.NoSourceLocation && loc.fileName == inputUnit.sourceFile.fileName
        then
          diagnostics +=
            makeDiagnostic(
              loc.position.line,
              loc.position.column,
              loc.position.line,
              loc.position.column,
              e.getMessage,
              e.statusCode.toString
            )
        else
          diagnostics += makeDiagnostic(1, 1, 1, 1, e.getMessage, e.statusCode.toString)
      case e: Throwable =>
        diagnostics +=
          makeDiagnostic(
            1,
            1,
            1,
            1,
            Option(e.getMessage).getOrElse(e.getClass.getName),
            StatusCode.INTERNAL_ERROR.toString
          )
    finally
      // Evict the transient snapshot so repeated requests on the long-lived compiler do not
      // accumulate stale symbols that shadow the workspace files
      lspCompiler.releaseUnit(inputUnit)
    end try

    given Weaver[LspDiagnostic] = Weaver.of[LspDiagnostic]
    summon[Weaver[List[LspDiagnostic]]].toJson(diagnostics.toList)

  end analyzeDiagnostics

  /**
    * Extract document symbols from a Wvlet source as JSON. Uses parse-only mode for speed.
    * @param content
    *   The Wvlet source code
    * @return
    *   JSON array of symbols: [{name, kind, startLine, startColumn, endLine, endColumn}]
    */
  @JSExport
  def getDocumentSymbols(content: String): String =
    val symbols   = ListBuffer.empty[LspSymbol]
    val inputUnit = CompilationUnit.fromWvletString(content)
    try
      inputUnit.unresolvedPlan = ParserPhase.parseOnly(inputUnit)
    catch
      case _: Throwable =>
      // Ignore parse errors — extract whatever symbols we can

    val sourceFile = inputUnit.sourceFile
    sourceFile.ensureLoaded

    def toSymbol(name: String, kind: Int, span: wvlet.lang.api.Span): LspSymbol =
      if span.exists then
        LspSymbol(
          name = name,
          kind = kind,
          startLine = sourceFile.offsetToLine(span.start) + 1,
          startColumn = sourceFile.offsetToColumn(span.start),
          endLine = sourceFile.offsetToLine(span.end) + 1,
          endColumn = sourceFile.offsetToColumn(span.end)
        )
      else
        LspSymbol(
          name = name,
          kind = kind,
          startLine = 1,
          startColumn = 1,
          endLine = 1,
          endColumn = 1
        )

    def extractSymbols(plan: LogicalPlan): Unit =
      plan match
        case pkg: PackageDef =>
          pkg.statements.foreach(extractSymbols)
        case m: ModelDef =>
          symbols += toSymbol(m.name.fullName, LspSymbolKind.Class, m.span)
        case t: TypeDef =>
          symbols += toSymbol(t.name.name, LspSymbolKind.Struct, t.span)
        case f: TopLevelFunctionDef =>
          symbols += toSymbol(f.functionDef.name.name, LspSymbolKind.Function, f.span)
        case v: ValDef =>
          symbols += toSymbol(v.name.name, LspSymbolKind.Variable, v.span)
        case p: PartialQueryDef =>
          symbols += toSymbol(p.name.name, LspSymbolKind.Function, p.span)
        case fl: FlowDef =>
          symbols += toSymbol(fl.name.name, LspSymbolKind.Function, fl.span)
        case _ =>
        // Skip other plan types

    extractSymbols(inputUnit.unresolvedPlan)

    given Weaver[LspSymbol] = Weaver.of[LspSymbol]
    summon[Weaver[List[LspSymbol]]].toJson(symbols.toList)

  end getDocumentSymbols

  /**
    * Compute code completion candidates for the given source at the given cursor position.
    *
    * @param content
    *   The Wvlet source code
    * @param line
    *   1-based line number of the cursor
    * @param column
    *   1-based column number of the cursor
    * @return
    *   JSON array of completion items: [{label, kind, detail}]. `kind` is an LSP
    *   `CompletionItemKind` numeric value. Returns at least keyword candidates even for invalid or
    *   incomplete input.
    */
  @JSExport
  def getCompletionItems(content: String, line: Int, column: Int): String =
    val items =
      try
        val sourceFile = CompilationUnit.fromWvletString(content).sourceFile
        sourceFile.ensureLoaded
        val offset = sourceFile.offsetAt(wvlet.lang.api.LinePosition(line, column))
        CompletionProvider.complete(content, offset, lspCompiler)
      catch
        case _: Throwable =>
          // Fall back to keyword candidates if the position cannot be resolved
          CompletionProvider.keywordItems

    given Weaver[CompletionItem] = Weaver.of[CompletionItem]
    summon[Weaver[List[CompletionItem]]].toJson(items)

  end getCompletionItems

  /**
    * Compute hover information (type / model signature) for the given source at the given cursor
    * position.
    *
    * @param content
    *   The Wvlet source code
    * @param line
    *   1-based line number of the cursor
    * @param column
    *   1-based column number of the cursor
    * @return
    *   JSON object `{content, startLine, startColumn, endLine, endColumn}` describing the hovered
    *   node, or the JSON literal `null` when there is nothing to show (unknown position, unresolved
    *   type, or incomplete input). `content` is markdown; line/column values are 1-based.
    */
  @JSExport
  def getHover(content: String, line: Int, column: Int): String =
    val result =
      try
        val sourceFile = CompilationUnit.fromWvletString(content).sourceFile
        sourceFile.ensureLoaded
        val offset = sourceFile.offsetAt(wvlet.lang.api.LinePosition(line, column))
        HoverProvider.hover(content, offset, lspCompiler)
      catch
        case _: Throwable =>
          None

    result match
      case Some(h) =>
        val hover = LspHover(
          content = h.content,
          startLine = h.startLine,
          startColumn = h.startColumn,
          endLine = h.endLine,
          endColumn = h.endColumn
        )
        Weaver.of[LspHover].toJson(hover)
      case None =>
        "null"

  end getHover

  /**
    * Compute the go-to-definition target (the model / type definition) for the given source at the
    * given cursor position.
    *
    * @param content
    *   The Wvlet source code
    * @param line
    *   1-based line number of the cursor
    * @param column
    *   1-based column number of the cursor
    * @return
    *   JSON object `{startLine, startColumn, endLine, endColumn, path?}` describing the 1-based
    *   source range of the definition, or the JSON literal `null` when the cursor is not on a
    *   resolvable model/type reference (unknown position, keyword, whitespace, the definition
    *   itself, or an unknown name). `path` is the local path of the workspace file containing the
    *   definition; it is absent when the definition is in the requested document itself.
    */
  @JSExport
  def getDefinition(content: String, line: Int, column: Int): String =
    val result =
      try
        val sourceFile = CompilationUnit.fromWvletString(content).sourceFile
        sourceFile.ensureLoaded
        val offset = sourceFile.offsetAt(wvlet.lang.api.LinePosition(line, column))
        DefinitionProvider.definition(content, offset, lspCompiler)
      catch
        case _: Throwable =>
          None

    result match
      case Some(d) =>
        val definition = LspDefinition(
          startLine = d.startLine,
          startColumn = d.startColumn,
          endLine = d.endLine,
          endColumn = d.endColumn,
          path = d.path
        )
        Weaver.of[LspDefinition].toJson(definition)
      case None =>
        "null"

  end getDefinition

end WvletJS

/**
  * Compilation options
  */
case class CompileOptions(target: Option[String] = None, profile: Option[String] = None)

/**
  * LSP diagnostic representation for JSON serialization
  */
case class LspDiagnostic(
    line: Int,
    column: Int,
    endLine: Int,
    endColumn: Int,
    message: String,
    severity: String,
    statusCode: String
)

/**
  * LSP symbol representation for JSON serialization
  */
case class LspSymbol(
    name: String,
    kind: Int,
    startLine: Int,
    startColumn: Int,
    endLine: Int,
    endColumn: Int
)

/**
  * LSP hover representation for JSON serialization. `content` is markdown text; the line/column
  * fields describe the 1-based source range of the hovered node.
  */
case class LspHover(content: String, startLine: Int, startColumn: Int, endLine: Int, endColumn: Int)

/**
  * LSP go-to-definition representation for JSON serialization. The line/column fields describe the
  * 1-based source range of the target model/type definition. `path` is the local path of the
  * workspace file containing the definition; it is `None` (absent in JSON) when the definition is
  * in the requested document itself.
  */
case class LspDefinition(
    startLine: Int,
    startColumn: Int,
    endLine: Int,
    endColumn: Int,
    path: Option[String] = None
)

/**
  * LSP SymbolKind constants (subset from the LSP specification)
  */
object LspSymbolKind:
  val Class: Int    = 5
  val Function: Int = 12
  val Variable: Int = 13
  val Struct: Int   = 23
