-- Test ALTER TABLE RENAME TO
ALTER TABLE users RENAME TO customers;

-- Test ALTER TABLE ADD COLUMN
ALTER TABLE users ADD COLUMN email VARCHAR;

-- Test ALTER TABLE DROP COLUMN
ALTER TABLE users DROP COLUMN email;

-- Test ALTER TABLE ALTER COLUMN TYPE (DuckDB syntax)
ALTER TABLE users ALTER age TYPE VARCHAR;

-- Test ALTER TABLE SET AUTHORIZATION
ALTER TABLE users SET AUTHORIZATION (USER admin);

-- Test Trino-style ALTER TABLE ADD COLUMN with options
ALTER TABLE users ADD COLUMN description VARCHAR NOT NULL COMMENT 'User description';

-- Test ALTER TABLE RENAME COLUMN
ALTER TABLE users RENAME COLUMN old_name TO new_name;

-- Test ALTER TABLE ALTER COLUMN SET DATA TYPE (Standard SQL)
ALTER TABLE users ALTER COLUMN age SET DATA TYPE INTEGER;

-- Test ALTER TABLE ALTER COLUMN SET DATA TYPE with USING (DuckDB)
ALTER TABLE users ALTER COLUMN i SET DATA TYPE VARCHAR USING concat(i, '_', j);

-- Test ALTER TABLE ALTER COLUMN DROP NOT NULL
ALTER TABLE users ALTER COLUMN age DROP NOT NULL;

-- Test ALTER TABLE SET PROPERTIES
ALTER TABLE users SET PROPERTIES format = 'parquet', compression = 'gzip';

-- Test ALTER TABLE EXECUTE
ALTER TABLE users EXECUTE optimize (max_file_size = 1000000) WHERE created_at < '2023-01-01';