-- Test ALTER TABLE RENAME TO
ALTER TABLE users RENAME TO customers;

-- Test ALTER TABLE IF EXISTS RENAME TO
ALTER TABLE IF EXISTS users RENAME TO customers;

-- Test ALTER TABLE ADD COLUMN
ALTER TABLE users ADD COLUMN email VARCHAR;

-- Test ALTER TABLE ADD COLUMN IF NOT EXISTS
ALTER TABLE users ADD COLUMN IF NOT EXISTS email VARCHAR;

-- Test ALTER TABLE DROP COLUMN
ALTER TABLE users DROP COLUMN email;

-- Test ALTER TABLE DROP COLUMN IF EXISTS
ALTER TABLE users DROP COLUMN IF EXISTS email;

-- Test ALTER TABLE ALTER COLUMN TYPE (DuckDB syntax)
ALTER TABLE users ALTER age TYPE VARCHAR;

-- Test ALTER TABLE IF EXISTS ALTER COLUMN TYPE
ALTER TABLE IF EXISTS users ALTER age TYPE VARCHAR;

-- Test ALTER TABLE SET AUTHORIZATION
ALTER TABLE users SET AUTHORIZATION (USER admin);

-- Test ALTER TABLE IF EXISTS SET AUTHORIZATION
ALTER TABLE IF EXISTS users SET AUTHORIZATION (USER admin);

-- Test ALTER TABLE IF EXISTS SET AUTHORIZATION with ROLE
ALTER TABLE IF EXISTS users SET AUTHORIZATION (ROLE data_team);

-- Test Trino-style ALTER TABLE ADD COLUMN with options
ALTER TABLE users ADD COLUMN description VARCHAR NOT NULL COMMENT 'User description';

-- Test ALTER TABLE IF EXISTS ADD COLUMN with options
ALTER TABLE IF EXISTS users ADD COLUMN description VARCHAR NOT NULL COMMENT 'User description';

-- Test ALTER TABLE IF EXISTS ADD COLUMN IF NOT EXISTS with options  
ALTER TABLE IF EXISTS users ADD COLUMN IF NOT EXISTS description VARCHAR NOT NULL COMMENT 'User description';

-- Test ALTER TABLE RENAME COLUMN
ALTER TABLE users RENAME COLUMN old_name TO new_name;

-- Test ALTER TABLE RENAME COLUMN IF EXISTS
ALTER TABLE users RENAME COLUMN IF EXISTS old_name TO new_name;

-- Test ALTER TABLE IF EXISTS RENAME COLUMN IF EXISTS
ALTER TABLE IF EXISTS users RENAME COLUMN IF EXISTS old_name TO new_name;

-- Test ALTER TABLE ALTER COLUMN SET DATA TYPE (Standard SQL)
ALTER TABLE users ALTER COLUMN age SET DATA TYPE INTEGER;

-- Test ALTER TABLE IF EXISTS ALTER COLUMN SET DATA TYPE
ALTER TABLE IF EXISTS users ALTER COLUMN age SET DATA TYPE INTEGER;

-- Test ALTER TABLE ALTER COLUMN SET DATA TYPE with USING (DuckDB)
ALTER TABLE users ALTER COLUMN i SET DATA TYPE VARCHAR USING concat(i, '_', j);

-- Test ALTER TABLE IF EXISTS ALTER COLUMN SET DATA TYPE with USING
ALTER TABLE IF EXISTS users ALTER COLUMN i SET DATA TYPE VARCHAR USING concat(i, '_', j);

-- Test ALTER TABLE ALTER COLUMN DROP NOT NULL
ALTER TABLE users ALTER COLUMN age DROP NOT NULL;

-- Test ALTER TABLE IF EXISTS ALTER COLUMN DROP NOT NULL
ALTER TABLE IF EXISTS users ALTER COLUMN age DROP NOT NULL;

-- Test ALTER TABLE ALTER COLUMN SET DEFAULT
ALTER TABLE users ALTER COLUMN age SET DEFAULT 18;

-- Test ALTER TABLE IF EXISTS ALTER COLUMN SET DEFAULT
ALTER TABLE IF EXISTS users ALTER COLUMN age SET DEFAULT 18;

-- Test ALTER TABLE ALTER COLUMN DROP DEFAULT
ALTER TABLE users ALTER COLUMN age DROP DEFAULT;

-- Test ALTER TABLE IF EXISTS ALTER COLUMN DROP DEFAULT
ALTER TABLE IF EXISTS users ALTER COLUMN age DROP DEFAULT;

-- Test ALTER TABLE ALTER COLUMN SET NOT NULL
ALTER TABLE users ALTER COLUMN age SET NOT NULL;

-- Test ALTER TABLE IF EXISTS ALTER COLUMN SET NOT NULL
ALTER TABLE IF EXISTS users ALTER COLUMN age SET NOT NULL;

-- Test ALTER TABLE SET PROPERTIES
ALTER TABLE users SET PROPERTIES format = 'parquet', compression = 'gzip';

-- Test ALTER TABLE IF EXISTS SET PROPERTIES
ALTER TABLE IF EXISTS users SET PROPERTIES format = 'parquet', compression = 'gzip';

-- Test ALTER TABLE IF EXISTS SET PROPERTIES with multiple properties
ALTER TABLE IF EXISTS users SET PROPERTIES format = 'orc', compression = 'snappy', partitioned_by = 'date';

-- Test ALTER TABLE EXECUTE
ALTER TABLE users EXECUTE optimize (max_file_size = 1000000) WHERE created_at < '2023-01-01';

-- Test ALTER TABLE IF EXISTS EXECUTE
ALTER TABLE IF EXISTS users EXECUTE optimize (max_file_size = 1000000) WHERE created_at < '2023-01-01';

-- Test ALTER TABLE IF EXISTS EXECUTE with different command
ALTER TABLE IF EXISTS users EXECUTE vacuum (full_scan = true);

-- Test ALTER TABLE IF EXISTS EXECUTE with no parameters
ALTER TABLE IF EXISTS users EXECUTE analyze;
