-- Test basic INTERVAL literals
SELECT INTERVAL '1' DAY;
SELECT INTERVAL '2' HOUR;
SELECT INTERVAL '30' MINUTE;
SELECT INTERVAL '45' SECOND;
SELECT INTERVAL '1' YEAR;
SELECT INTERVAL '6' MONTH;

-- Test signed INTERVAL literals
SELECT INTERVAL + '1' DAY;
SELECT INTERVAL - '1' DAY;
SELECT INTERVAL + '2' HOUR;
SELECT INTERVAL - '30' MINUTE;

-- Test range INTERVAL literals (DAY TO HOUR, etc.)
SELECT INTERVAL '1' DAY TO HOUR;
SELECT INTERVAL '1' HOUR TO MINUTE;
SELECT INTERVAL '1' MINUTE TO SECOND;
SELECT INTERVAL '1' YEAR TO MONTH;

-- Test in arithmetic expressions
SELECT DATE '2023-01-01' + INTERVAL '1' DAY;
SELECT TIMESTAMP '2023-01-01 12:00:00' - INTERVAL '1' HOUR;

-- Test in WHERE clauses
SELECT * FROM orders WHERE order_date > CURRENT_DATE - INTERVAL '30' DAY;