const esbuild = require('esbuild');
const fs = require('fs');
const path = require('path');

const isWatch = process.argv.includes('--watch');

// The language server (src/server.ts) dynamically imports the Scala.js
// compiler bundle, which is generated by `./sbt sdkJs/fastLinkJS` and is NOT
// checked into git. If the file is missing, esbuild does NOT fail: it silently
// leaves the unresolvable dynamic import in place, producing a package whose
// language server can never load the compiler (this shipped as the broken
// 2026.1.0 release). Fail hard instead.
const compilerBundle = path.resolve(
  __dirname,
  '../sdks/typescript/lib/main.js'
);
if (!fs.existsSync(compilerBundle)) {
  console.error(
    `ERROR: Scala.js compiler bundle not found: ${compilerBundle}\n` +
      'The language server cannot be packaged without it.\n' +
      'Build it first with: ./sbt "sdkJs/fastLinkJS" (from the repository root)'
  );
  process.exit(1);
}

// The Scala.js compiler bundle (sdks/typescript/lib/main.js) statically imports
// `koffi`, the native FFI used only by the DuckDB query connector. The language
// server never executes queries, so that binding is never referenced. Bundling
// koffi as CJS breaks it (its `createRequire(import.meta.url)` resolves to
// undefined, and its native `.node` addons cannot be inlined). Replace koffi
// with an empty stub so the bundle stays self-contained and side-effect free.
const stubKoffiPlugin = {
  name: 'stub-koffi',
  setup(build) {
    build.onResolve({ filter: /^koffi$/ }, () => ({
      path: 'koffi',
      namespace: 'stub-koffi',
    }));
    build.onLoad({ filter: /.*/, namespace: 'stub-koffi' }, () => ({
      contents: 'export default {};',
      loader: 'js',
    }));
  },
};

/** @type {import('esbuild').BuildOptions} */
const extensionConfig = {
  entryPoints: ['src/extension.ts'],
  bundle: true,
  outfile: 'out/extension.js',
  external: ['vscode'],
  format: 'cjs',
  platform: 'node',
  target: 'node18',
  sourcemap: true,
};

/** @type {import('esbuild').BuildOptions} */
const serverConfig = {
  entryPoints: ['src/server.ts'],
  bundle: true,
  outfile: 'out/server.js',
  format: 'cjs',
  platform: 'node',
  target: 'node18',
  sourcemap: true,
  plugins: [stubKoffiPlugin],
};

async function build() {
  if (isWatch) {
    const extCtx = await esbuild.context(extensionConfig);
    const srvCtx = await esbuild.context(serverConfig);
    await Promise.all([extCtx.watch(), srvCtx.watch()]);
    console.log('Watching for changes...');
  } else {
    await Promise.all([
      esbuild.build(extensionConfig),
      esbuild.build(serverConfig),
    ]);
    console.log('Build complete.');
  }
}

build().catch((e) => {
  console.error(e);
  process.exit(1);
});
