/**
 * Type definitions for Scala.js generated WvletJS module
 */

export interface WvletJSType {
  /**
   * Compile a Wvlet query and return the result as JSON
   * @param query The Wvlet query string
   * @param options JSON string with compilation options
   * @returns JSON string with compilation result
   */
  compile(query: string, options?: string): string;
  
  /**
   * Get the version of the Wvlet compiler
   * @returns The version string
   */
  getVersion(): string;

  /**
   * Set the workspace root folder for LSP features. Sources in the folder — including the
   * catalog/ folder generated by `wvlet catalog import` — are compiled together with each
   * document, enabling offline table/column resolution and cross-file references
   * @param path The workspace root folder path
   */
  setWorkspacePath(path: string): void;

  /**
   * Analyze a Wvlet source and return diagnostics as JSON
   * @param content The Wvlet source code
   * @returns JSON array of diagnostics
   */
  analyzeDiagnostics(content: string): string;

  /**
   * Extract document symbols from a Wvlet source as JSON
   * @param content The Wvlet source code
   * @returns JSON array of symbols
   */
  getDocumentSymbols(content: string): string;

  /**
   * Compute code completion candidates for a Wvlet source at the given cursor position as JSON
   * @param content The Wvlet source code
   * @param line 1-based line number of the cursor
   * @param column 1-based column number of the cursor
   * @returns JSON array of completion items ({label, kind, detail})
   */
  getCompletionItems(content: string, line: number, column: number): string;

  /**
   * Compute hover information (type / model signature) for a Wvlet source at the given cursor position as JSON
   * @param content The Wvlet source code
   * @param line 1-based line number of the cursor
   * @param column 1-based column number of the cursor
   * @returns JSON object ({content, startLine, startColumn, endLine, endColumn}) or the literal `null` when there is nothing to show
   */
  getHover(content: string, line: number, column: number): string;

  /**
   * Compute the go-to-definition target (model / type definition) for a Wvlet source at the given cursor position as JSON
   * @param content The Wvlet source code
   * @param line 1-based line number of the cursor
   * @param column 1-based column number of the cursor
   * @returns JSON object ({startLine, startColumn, endLine, endColumn}) or the literal `null` when there is nothing to resolve
   */
  getDefinition(content: string, line: number, column: number): string;
}

export const WvletJS: WvletJSType;
export const log: any;