/*
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *    http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */
package wvlet.lang.compiler.typer

import wvlet.uni.test.UniTest
import wvlet.lang.compiler.CompilationUnit
import wvlet.lang.compiler.CompileResult
import wvlet.lang.compiler.Compiler
import wvlet.lang.compiler.CompilerOptions
import wvlet.lang.compiler.WorkEnv

/**
  * Static-catalog warnings for destructive DDL (#1999): when `table ... in <catalog>.<schema>`
  * declarations (as generated by `wvlet catalog import`) cover a location, a `drop table` /
  * `reshape` / `truncate` targeting an unknown table in that location warns — but never errors,
  * since the imported snapshot may be stale
  */
class StaticCatalogDdlWarningTest extends UniTest:

  private val importedCatalog =
    """table orders in mydb.sales = {
      |  order_id: bigint
      |  status: string
      |}
      |""".stripMargin

  private def compile(defs: String, query: String): CompilationUnit =
    val compiler  = Compiler(CompilerOptions(workEnv = WorkEnv(".")))
    val defsUnit  = CompilationUnit.fromWvletString(defs)
    val queryUnit = CompilationUnit.fromWvletString(query)
    compiler.compileMultipleUnits(List(defsUnit), queryUnit)
    queryUnit

  private def warnings(unit: CompilationUnit): List[UnknownStaticCatalogTarget] = unit
    .typerErrors
    .collect { case w: UnknownStaticCatalogTarget =>
      w
    }

  test("warn on dropping a table the imported catalog does not know") {
    val unit = compile(importedCatalog, "drop table sales.unknown_table\n")
    val ws   = warnings(unit)
    ws.size shouldBe 1
    ws.head.severity shouldBe TyperError.Severity.Warning
    ws.head.message shouldContain "sales.unknown_table"
    ws.head.message shouldContain "wvlet catalog import"
  }

  test("stay silent on dropping a declared table") {
    warnings(compile(importedCatalog, "drop table sales.orders\n")) shouldBe Nil
  }

  test("stay silent when if exists acknowledges the table may be missing") {
    warnings(compile(importedCatalog, "drop table sales.unknown_table if exists\n")) shouldBe Nil
  }

  test("warn on reshaping an unknown table") {
    val ws = warnings(
      compile(importedCatalog, "reshape sales.unknown_table {\n  add note: string\n}\n")
    )
    ws.size shouldBe 1
    ws.head.statement shouldBe "reshape"
  }

  test("stay silent on reshaping a declared table") {
    warnings(compile(importedCatalog, "reshape sales.orders {\n  add note: string\n}\n")) shouldBe
      Nil
  }

  test("warn on truncating an unknown table") {
    val ws = warnings(compile(importedCatalog, "truncate sales.unknown_table\n"))
    ws.size shouldBe 1
    ws.head.statement shouldBe "truncate"
  }

  test("stay silent without any imported catalog") {
    val plainDecl = "table local_t = {\n  id: int\n}\n"
    warnings(compile(plainDecl, "drop table some_other_table\n")) shouldBe Nil
  }

  test("stay silent for locations outside the imported catalog") {
    warnings(compile(importedCatalog, "drop table other_schema.some_table\n")) shouldBe Nil
  }

  test("never fail the compilation, even in strict mode") {
    val compiler  = Compiler(CompilerOptions(workEnv = WorkEnv(".")))
    val defsUnit  = CompilationUnit.fromWvletString(importedCatalog)
    val queryUnit = CompilationUnit.fromWvletString("drop table sales.unknown_table\n")
    val result    = compiler.compileMultipleUnits(List(defsUnit), queryUnit)
    result.hasFailures shouldBe false
    warnings(queryUnit).size shouldBe 1
  }

end StaticCatalogDdlWarningTest
