name: highlight.js

on:
  push:
    branches: [ main ]
    paths:
      - 'highlightjs-wvlet/**'
      - '.github/workflows/highlightjs.yml'
  pull_request:
    branches: [ main ]
    paths:
      - 'highlightjs-wvlet/**'
      - '.github/workflows/highlightjs.yml'

jobs:
  test:
    name: highlight.js
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: highlightjs-wvlet
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Use Node.js
      uses: actions/setup-node@v4
      with:
        node-version: 22
        cache: 'npm'
        cache-dependency-path: package-lock.json
    
    - name: Install dependencies
      run: npm ci
    
    - name: Build
      run: npm run build
    
    - name: Run tests
      run: npm test
    
    - name: Run markup tests
      run: npm run mocha
    
    - name: Verify dist files
      run: |
        if [ ! -f "dist/wvlet.js" ]; then
          echo "dist/wvlet.js not found!"
          exit 1
        fi
        if [ ! -f "dist/wvlet.min.js" ]; then
          echo "dist/wvlet.min.js not found!"
          exit 1
        fi
        echo "✅ Dist files generated successfully"