name: highlight.js

on:
  pull_request:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  changes:
    runs-on: ubuntu-latest
    permissions:
      pull-requests: read
    outputs:
      highlightjs: ${{ steps.filter.outputs.highlightjs }}
    steps:
      - uses: actions/checkout@v5
      - uses: dorny/paths-filter@v3
        id: filter
        with:
          filters: |
            highlightjs:
              - 'highlightjs-wvlet/**'
              - '.github/workflows/highlightjs.yml'
  
  test:
    name: highlight.js
    needs: changes
    if: ${{ needs.changes.outputs.highlightjs == 'true' }}
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: highlightjs-wvlet
    
    steps:
    - uses: actions/checkout@v5
    
    - name: Use Node.js
      uses: actions/setup-node@v6
      with:
        node-version: 22
        cache: 'npm'
        cache-dependency-path: package-lock.json
    
    - name: Install dependencies
      run: npm ci
    
    - name: Build
      run: npm run build
    
    - name: Run tests
      run: npm test
    
    - name: Run markup tests
      run: npm run mocha
    
    - name: Verify dist files
      run: |
        if [ ! -f "dist/wvlet.js" ]; then
          echo "dist/wvlet.js not found!"
          exit 1
        fi
        if [ ! -f "dist/wvlet.min.js" ]; then
          echo "dist/wvlet.min.js not found!"
          exit 1
        fi
        echo "✅ Dist files generated successfully"