name: Publish to NPM

on:
  release:
    types: [created]
  workflow_dispatch:
    inputs:
      version:
        description: 'Version to publish (e.g., 0.1.0)'
        required: true
        type: string

jobs:
  publish:
    name: Publish TypeScript SDK to NPM
    runs-on: ubuntu-latest
    permissions:
      contents: read
      id-token: write
    
    steps:
      - uses: actions/checkout@v4
      
      - name: Set up Java
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '24'
          cache: sbt
      
      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 22
          registry-url: 'https://registry.npmjs.org'
      
      - name: Build Scala.js SDK
        run: ./sbt "sdkJs/fullLinkJS"
      
      - name: Install dependencies
        working-directory: sdks/typescript
        run: npm install
      
      - name: Build TypeScript
        working-directory: sdks/typescript
        run: npm run build
      
      - name: Run tests
        working-directory: sdks/typescript
        run: npm run test:ci
      
      - name: Set version from release
        if: github.event_name == 'release'
        working-directory: sdks/typescript
        run: |
          VERSION=$(echo "${{ github.ref }}" | sed 's/refs\/tags\/v//')
          npm version $VERSION --no-git-tag-version
      
      - name: Set version from input
        if: github.event_name == 'workflow_dispatch'
        working-directory: sdks/typescript
        run: |
          npm version ${{ inputs.version }} --no-git-tag-version
      
      - name: Publish to NPM
        working-directory: sdks/typescript
        run: npm publish --provenance --access public
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}