name: Build and Publish Python SDK

on:
  push:
    branches:
      - main
    tags:
      - 'v*'
  pull_request:
    paths:
      - 'sdks/python/**'
      - '.github/workflows/python-publish.yml'
  workflow_dispatch:

jobs:
  build-wheels:
    name: Build Python wheels
    strategy:
      matrix:
        include:
          - os: ubuntu-latest
            platform: linux
            arch: x86_64
          - os: ubuntu-latest
            platform: linux  
            arch: aarch64
          - os: macos-latest
            platform: macos
            arch: arm64
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0  # Fetch all tags for setuptools_scm
      
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'
      
      # First, try to download native library artifacts from latest workflow
      - name: Download native library artifacts from latest workflow
        uses: dawidd6/action-download-artifact@v6
        continue-on-error: true
        id: download-artifacts
        with:
          workflow: native.yml
          workflow_conclusion: success
          name: wvc-lib
          path: native-libs/
          if_no_artifact_found: warn
      
      # If artifacts don't exist, create dummy libraries for testing
      - name: Create dummy native libraries if artifacts not found
        if: steps.download-artifacts.outcome != 'success'
        run: |
          echo "Native artifacts not found, creating dummy libraries for testing"
          mkdir -p native-libs/linux-x64
          mkdir -p native-libs/linux-arm64
          mkdir -p native-libs/mac-arm64
          touch native-libs/linux-x64/libwvlet.so
          touch native-libs/linux-arm64/libwvlet.so
          touch native-libs/mac-arm64/libwvlet.dylib
      
      - name: Display structure of downloaded files
        run: |
          if [ -d "native-libs" ]; then
            ls -laR native-libs/
          else
            echo "No native-libs directory found"
          fi
      
      - name: Copy native libraries to Python package
        run: |
          # Create directories for each platform
          mkdir -p sdks/python/wvlet/libs/linux_x86_64
          mkdir -p sdks/python/wvlet/libs/linux_aarch64
          mkdir -p sdks/python/wvlet/libs/darwin_arm64
          
          # Copy the libraries to the appropriate directories if they exist
          if [ -f "native-libs/linux-x64/libwvlet.so" ]; then
            cp native-libs/linux-x64/libwvlet.so sdks/python/wvlet/libs/linux_x86_64/
          else
            echo "Warning: linux-x64 library not found, creating placeholder"
            touch sdks/python/wvlet/libs/linux_x86_64/libwvlet.so
          fi
          
          if [ -f "native-libs/linux-arm64/libwvlet.so" ]; then
            cp native-libs/linux-arm64/libwvlet.so sdks/python/wvlet/libs/linux_aarch64/
          else
            echo "Warning: linux-arm64 library not found, creating placeholder"
            touch sdks/python/wvlet/libs/linux_aarch64/libwvlet.so
          fi
          
          if [ -f "native-libs/mac-arm64/libwvlet.dylib" ]; then
            cp native-libs/mac-arm64/libwvlet.dylib sdks/python/wvlet/libs/darwin_arm64/
          else
            echo "Warning: mac-arm64 library not found, creating placeholder"
            touch sdks/python/wvlet/libs/darwin_arm64/libwvlet.dylib
          fi
          
          # Display the final structure
          ls -laR sdks/python/wvlet/libs/
      
      - name: Ad-hoc sign macOS library
        if: matrix.platform == 'macos'
        run: |
          echo "Signing macOS library with ad-hoc signature..."
          # Sign the library
          codesign --sign - --force sdks/python/wvlet/libs/darwin_arm64/libwvlet.dylib
          
          # Remove quarantine attribute if present
          xattr -cr sdks/python/wvlet/libs/darwin_arm64/libwvlet.dylib || true
          
          # Verify signature
          codesign --verify --verbose sdks/python/wvlet/libs/darwin_arm64/libwvlet.dylib
          
          # Display signature info
          codesign --display --verbose=2 sdks/python/wvlet/libs/darwin_arm64/libwvlet.dylib
      
      - name: Install build dependencies
        run: |
          python -m pip install --upgrade pip
          pip install build wheel setuptools
      
      - name: Build source distribution
        if: matrix.platform == 'linux' && matrix.arch == 'x86_64'
        run: |
          cd sdks/python
          python -m build --sdist
      
      - name: Install wheel building tools
        run: |
          if [ "${{ matrix.platform }}" = "macos" ]; then
            pip install delocate
          fi
      
      - name: Build platform-specific wheels
        run: |
          cd sdks/python
          
          if [ "${{ matrix.platform }}" = "linux" ]; then
            # Build wheels for Linux
            python -m build --wheel
            
            # Rename the wheel to be platform-specific
            cd dist
            for wheel in *.whl; do
              # Extract wheel name components
              name=$(echo $wheel | cut -d'-' -f1)
              version=$(echo $wheel | cut -d'-' -f2)
              
              # Create platform-specific wheel based on architecture
              if [ "${{ matrix.arch }}" = "x86_64" ]; then
                mv $wheel ${name}-${version}-py3-none-manylinux2014_x86_64.whl
              else
                mv $wheel ${name}-${version}-py3-none-manylinux2014_aarch64.whl
              fi
            done
            cd ..
          elif [ "${{ matrix.platform }}" = "macos" ]; then
            # Build wheel for macOS
            python -m build --wheel
            
            # Use delocate to create proper macOS wheel
            cd dist
            for wheel in *.whl; do
              # Rename to platform-specific name first
              name=$(echo $wheel | cut -d'-' -f1)
              version=$(echo $wheel | cut -d'-' -f2)
              mv $wheel ${name}-${version}-py3-none-macosx_11_0_arm64.whl
            done
            
            # Run delocate to ensure proper library bundling
            delocate-wheel -v *.whl
            cd ..
          fi
          
          # Display the wheels
          ls -la dist/
          
      
      - name: Display built distributions
        run: ls -la sdks/python/dist/
      
      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: python-distributions
          path: sdks/python/dist/

  test-wheels:
    name: Test wheels on ${{ matrix.os }}
    needs: build-wheels
    strategy:
      matrix:
        os: [ubuntu-latest, ubuntu-24.04-arm]
        python-version: ['3.9', '3.11', '3.13']
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0  # Fetch all tags for setuptools_scm
      
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}
      
      - name: Download built wheels
        uses: actions/download-artifact@v4
        with:
          name: python-distributions
          path: dist/
      
      - name: List available wheels
        run: |
          echo "Available wheels:"
          ls -la dist/
      
      - name: Install wheel
        run: |
          # Install the appropriate wheel for this platform
          if [[ "${{ runner.arch }}" == "ARM64" ]]; then
            echo "Installing ARM64 wheel..."
            pip install dist/wvlet-*-py3-none-manylinux2014_aarch64.whl
          else
            echo "Installing x86_64 wheel..."
            pip install dist/wvlet-*-py3-none-manylinux2014_x86_64.whl
          fi
      
      - name: Test import
        run: |
          python -c "from wvlet import compile; print('Import successful')"
      
      - name: Run tests
        run: |
          pip install pytest
          cd sdks/python
          pytest tests/

  publish:
    name: Publish to PyPI
    needs: test-wheels
    runs-on: ubuntu-latest
    # Only publish on tagged releases
    if: github.event_name == 'push' && startsWith(github.ref, 'refs/tags/v')
    environment:
      name: pypi
      url: https://pypi.org/p/wvlet
    permissions:
      id-token: write  # For PyPI trusted publishing
    steps:
      - name: Download built distributions
        uses: actions/download-artifact@v4
        with:
          name: python-distributions
          path: dist/
      
      - name: Display distributions to publish
        run: ls -la dist/
      
      - name: Publish to PyPI
        uses: pypa/gh-action-pypi-publish@release/v1
        with:
          packages-dir: dist/
          skip-existing: true