name: VS Code Extension

on:
  push:
    branches: [ main ]
    paths: [ 'vscode-wvlet/**' ]
  pull_request:
    branches: [ main ]
    paths: [ 'vscode-wvlet/**' ]
  release:
    types: [ published ]

jobs:
  build:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: vscode-wvlet
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '18'
        cache: 'npm'
        cache-dependency-path: vscode-wvlet/package-lock.json
    
    - name: Install dependencies
      run: npm ci
    
    - name: Package extension
      run: npm run package
    
    - name: Upload VSIX artifact
      uses: actions/upload-artifact@v4
      with:
        name: vscode-extension
        path: vscode-wvlet/*.vsix
        retention-days: 30
    
    - name: Publish to VS Code Marketplace (on release)
      if: github.event_name == 'release'
      run: npx vsce publish --pat ${{ secrets.VSCE_PAT }}
      env:
        VSCE_PAT: ${{ secrets.VSCE_PAT }}